# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget libbot2::lcmtypes_bot2-procman libbot2::bot-procman-deputy)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target libbot2::lcmtypes_bot2-procman
add_library(libbot2::lcmtypes_bot2-procman STATIC IMPORTED)

set_target_properties(libbot2::lcmtypes_bot2-procman PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/argsubt/subt-system/procman/bot2-procman/pod-build/include/lcmtypes;/home/argsubt/subt-system/procman/bot2-procman/pod-build/include"
  INTERFACE_LINK_LIBRARIES "lcm-coretypes;lcm"
)

# Create imported target libbot2::bot-procman-deputy
add_executable(libbot2::bot-procman-deputy IMPORTED)

# Import target "libbot2::lcmtypes_bot2-procman" for configuration "Release"
set_property(TARGET libbot2::lcmtypes_bot2-procman APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libbot2::lcmtypes_bot2-procman PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/argsubt/subt-system/procman/bot2-procman/pod-build/lib/liblcmtypes_bot2-procman.a"
  )

# Import target "libbot2::bot-procman-deputy" for configuration "Release"
set_property(TARGET libbot2::bot-procman-deputy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libbot2::bot-procman-deputy PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/argsubt/subt-system/procman/bot2-procman/pod-build/bin/bot-procman-deputy"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
